# .tbls.yml

# DSN (Databaase Source Name) to connect database
dsn: postgres://postgres:dalong@localhost:5432/postgres?sslmode=disable

# Path to generate document
# Default is `dbdoc`
docPath: doc/schema